package RhythmEx;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.event.*;
public class Game extends Thread {
	private Image KeyUp = new ImageIcon(Main.class.getResource("../images/KeyUp.png")).getImage();
	private Image KeyDown = new ImageIcon(Main.class.getResource("../images/KeyDown.png")).getImage();
	private Image KeyLeft = new ImageIcon(Main.class.getResource("../images/KeyLeft.png")).getImage();
	private Image KeyRight = new ImageIcon(Main.class.getResource("../images/KeyRight.png")).getImage();
	private Image flareimage;
	private Image judgeimage;

	private String titleName;
	private String difficulty;
	private String musicTitle;
	private Music gameMusic;
	private int Score=0;
	
	ArrayList<Note> noteList = new ArrayList<Note>();
	public Game(String titleName,String difficulty,String musicTitle){
		this.titleName = titleName;
		this.difficulty = difficulty;
		this.musicTitle = musicTitle;
		gameMusic = new Music(this.musicTitle,false);

	}
		public void screenDraw(Graphics g){	
		g.drawImage(KeyLeft,460,115,null);
		g.drawImage(KeyDown,560,115,null);
		g.drawImage(KeyUp,660,115,null);
		g.drawImage(KeyRight,760,115,null);
		for(int i =0; i<noteList.size();i++){
			Note note = noteList.get(i);
			if(note.getY()<53){
				judgeimage = new ImageIcon(Main.class.getResource("../images/miss.png")).getImage();
			}
			if(!note.isProceeded()){
				noteList.remove(i);
				i--;
			}else{
			note.screenDraw(g);
			}
		}
		Font f = new Font("Elephant",Font.BOLD,30);
		g.setColor(Color.WHITE);
		g.setFont(f);
		g.drawString(Integer.toString(Score),1000 , 35);
		g.drawImage(flareimage, 475, 250, null);
		g.drawImage(judgeimage, 528, 240, null);
		
	}
	public void pressUp(){
		judge("Up");
		KeyUp = new ImageIcon(Main.class.getResource("../images/KeyUpPressed.png")).getImage();
	}
	public void pressDown(){
		judge("Down");
		KeyDown = new ImageIcon(Main.class.getResource("../images/KeyDownPressed.png")).getImage();
	}
	public void pressLeft(){
		judge("Left");
		KeyLeft = new ImageIcon(Main.class.getResource("../images/KeyLeftPressed.png")).getImage();
	}
	public void pressRight(){
		judge("Right");
		KeyRight = new ImageIcon(Main.class.getResource("../images/KeyRightPressed.png")).getImage();
	}
	public void releaseUp(){
		KeyUp = new ImageIcon(Main.class.getResource("../images/KeyUp.png")).getImage();
	}
	public void releaseDown(){
		KeyDown = new ImageIcon(Main.class.getResource("../images/KeyDown.png")).getImage();
	}
	public void releaseLeft(){
		KeyLeft = new ImageIcon(Main.class.getResource("../images/KeyLeft.png")).getImage();
	}
	public void releaseRight(){
		KeyRight = new ImageIcon(Main.class.getResource("../images/KeyRight.png")).getImage();
	}
	public void run(){
		raiseNote();
	}
	public void close(){
		gameMusic.close();
		this.interrupt();
	}
	public void raiseNote(){

		Beat[] beats = null;
		if(titleName.equals("fire")&&difficulty.equals("easy")){
			int startTime = 2500-Main.REACH_TIME*1000;
			int gap = 500;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Left"),
					new Beat(startTime+gap*22,"Left"),
					new Beat(startTime+gap*24,"Down"),
					new Beat(startTime+gap*26,"Left"),
					new Beat(startTime+gap*28,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Up"),
					new Beat(startTime+gap*34,"Down"),
					new Beat(startTime+gap*36,"Left"),
					new Beat(startTime+gap*38,"Right"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*44,"Right"),
					new Beat(startTime+gap*46,"Up"),
					new Beat(startTime+gap*48,"Right"),
					new Beat(startTime+gap*50,"Left"),
					new Beat(startTime+gap*52,"Left"),
					new Beat(startTime+gap*54,"Down"),
					new Beat(startTime+gap*56,"Left"),
					new Beat(startTime+gap*58,"Right"),
					new Beat(startTime+gap*60,"Up"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Down"),
					new Beat(startTime+gap*66,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Down"),
					new Beat(startTime+gap*74,"Right"),
					new Beat(startTime+gap*76,"Up"),
					new Beat(startTime+gap*78,"Right"),
					new Beat(startTime+gap*80,"Left"),
					new Beat(startTime+gap*82,"Left"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Left"),
					new Beat(startTime+gap*88,"Right"),
					new Beat(startTime+gap*90,"Up"),
					new Beat(startTime+gap*92,"Up"),
					new Beat(startTime+gap*94,"Down"),
					new Beat(startTime+gap*96,"Left"),
					new Beat(startTime+gap*98,"Right"),
					new Beat(startTime+gap*100,"Down"),
					new Beat(startTime+gap*102,"Down"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Right"),
					new Beat(startTime+gap*110,"Down"),
					new Beat(startTime+gap*112,"Down"),
					new Beat(startTime+gap*114,"Right"),
					new Beat(startTime+gap*116,"Up"),
					new Beat(startTime+gap*118,"Right"),
					new Beat(startTime+gap*120,"Left"),
					new Beat(startTime+gap*122,"Left"),
					new Beat(startTime+gap*124,"Down"),
					new Beat(startTime+gap*126,"Left"),
					new Beat(startTime+gap*128,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Up"),
					new Beat(startTime+gap*134,"Down"),
					new Beat(startTime+gap*136,"Left"),
					new Beat(startTime+gap*138,"Right"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*142,"Down"),
					new Beat(startTime+gap*144,"Right"),
					new Beat(startTime+gap*146,"Up"),
					new Beat(startTime+gap*148,"Right"),
					new Beat(startTime+gap*150,"Left"),
					new Beat(startTime+gap*152,"Left"),
					new Beat(startTime+gap*154,"Down"),
					new Beat(startTime+gap*156,"Left"),
					new Beat(startTime+gap*158,"Right"),
					new Beat(startTime+gap*160,"Up"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Down"),
					new Beat(startTime+gap*166,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Down"),
					new Beat(startTime+gap*174,"Right"),
					new Beat(startTime+gap*176,"Up"),
					new Beat(startTime+gap*178,"Right"),
					new Beat(startTime+gap*180,"Left"),
					new Beat(startTime+gap*182,"Left"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Left"),
					new Beat(startTime+gap*188,"Right"),
					new Beat(startTime+gap*190,"Up"),
					new Beat(startTime+gap*192,"Up"),
					new Beat(startTime+gap*194,"Down"),
					new Beat(startTime+gap*196,"Left"),
					new Beat(startTime+gap*198,"Right"),
					new Beat(startTime+gap*200,"Down"),
					new Beat(startTime+gap*202,"Down"),
					new Beat(startTime+gap*204,"Right"),
					new Beat(startTime+gap*206,"Up"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Left"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Down"),
					new Beat(startTime+gap*222,"Left"),
					new Beat(startTime+gap*224,"Down"),
					new Beat(startTime+gap*226,"Left"),
					new Beat(startTime+gap*228,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Up"),
					new Beat(startTime+gap*234,"Down"),
					new Beat(startTime+gap*236,"Left"),
					new Beat(startTime+gap*238,"Right"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*244,"Right")
					
					
					
			};
		}
		if(titleName.equals("fire")&&difficulty.equals("hard")){
			int startTime =  1000-Main.REACH_TIME*1000;
			int gap = 250;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Up"),
					new Beat(startTime+gap*21,"Up"),
					new Beat(startTime+gap*22,"Down"),
					new Beat(startTime+gap*24,"Left"),
					new Beat(startTime+gap*26,"Right"),
					new Beat(startTime+gap*27,"Down"),
					new Beat(startTime+gap*28,"Down"),
					new Beat(startTime+gap*30,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Left"),
					new Beat(startTime+gap*33,"Up"),
					new Beat(startTime+gap*34,"Up"),
					new Beat(startTime+gap*36,"Right"),
					new Beat(startTime+gap*38,"Up"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*41,"Up"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*42,"Right"),
					new Beat(startTime+gap*43,"Left"),
					new Beat(startTime+gap*45,"Right"),
					new Beat(startTime+gap*46,"Down"),
					new Beat(startTime+gap*48,"Down"),
					new Beat(startTime+gap*50,"Right"),
					new Beat(startTime+gap*52,"Up"),
					new Beat(startTime+gap*54,"Left"),
					new Beat(startTime+gap*56,"Up"),
					new Beat(startTime+gap*57,"Left"),
					new Beat(startTime+gap*59,"Right"),
					new Beat(startTime+gap*61,"Up"),
					new Beat(startTime+gap*62,"Down"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Up"),
					new Beat(startTime+gap*66,"Down"),
					new Beat(startTime+gap*67,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Left"),
					new Beat(startTime+gap*72,"Right"),
					new Beat(startTime+gap*74,"Up"),
					new Beat(startTime+gap*75,"Left"),
					new Beat(startTime+gap*77,"Up"),
					new Beat(startTime+gap*79,"Up"),
					new Beat(startTime+gap*81,"Right"),
					new Beat(startTime+gap*82,"Up"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Up"),
					new Beat(startTime+gap*88,"Up"),
					new Beat(startTime+gap*90,"Down"),
					new Beat(startTime+gap*92,"Left"),
					new Beat(startTime+gap*94,"Right"),
					new Beat(startTime+gap*96,"Down"),
					new Beat(startTime+gap*98,"Down"),
					new Beat(startTime+gap*99,"Right"),
					new Beat(startTime+gap*100,"Up"),
					new Beat(startTime+gap*101,"Left"),
					new Beat(startTime+gap*102,"Up"),
					new Beat(startTime+gap*103,"Up"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Down"),
					new Beat(startTime+gap*110,"Up"),
					new Beat(startTime+gap*120,"Up"),
					new Beat(startTime+gap*121,"Up"),
					new Beat(startTime+gap*122,"Down"),
					new Beat(startTime+gap*124,"Left"),
					new Beat(startTime+gap*126,"Right"),
					new Beat(startTime+gap*127,"Down"),
					new Beat(startTime+gap*128,"Down"),
					new Beat(startTime+gap*130,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Left"),
					new Beat(startTime+gap*133,"Up"),
					new Beat(startTime+gap*134,"Up"),
					new Beat(startTime+gap*136,"Right"),
					new Beat(startTime+gap*138,"Up"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*141,"Up"),
					new Beat(startTime+gap*142,"Up"),
					new Beat(startTime+gap*142,"Left"),
					new Beat(startTime+gap*143,"Left"),
					new Beat(startTime+gap*145,"Right"),
					new Beat(startTime+gap*146,"Down"),
					new Beat(startTime+gap*148,"Down"),
					new Beat(startTime+gap*150,"Right"),
					new Beat(startTime+gap*152,"Up"),
					new Beat(startTime+gap*154,"Left"),
					new Beat(startTime+gap*156,"Up"),
					new Beat(startTime+gap*157,"Left"),
					new Beat(startTime+gap*159,"Right"),
					new Beat(startTime+gap*161,"Up"),
					new Beat(startTime+gap*162,"Down"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Up"),
					new Beat(startTime+gap*166,"Down"),
					new Beat(startTime+gap*167,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Left"),
					new Beat(startTime+gap*172,"Right"),
					new Beat(startTime+gap*174,"Up"),
					new Beat(startTime+gap*175,"Left"),
					new Beat(startTime+gap*177,"Up"),
					new Beat(startTime+gap*179,"Up"),
					new Beat(startTime+gap*181,"Right"),
					new Beat(startTime+gap*182,"Up"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Up"),
					new Beat(startTime+gap*188,"Up"),
					new Beat(startTime+gap*190,"Down"),
					new Beat(startTime+gap*192,"Left"),
					new Beat(startTime+gap*194,"Right"),
					new Beat(startTime+gap*196,"Down"),
					new Beat(startTime+gap*198,"Down"),
					new Beat(startTime+gap*199,"Right"),
					new Beat(startTime+gap*202,"Up"),
					new Beat(startTime+gap*204,"Down"),
					new Beat(startTime+gap*206,"Left"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Down"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Up"),
					new Beat(startTime+gap*221,"Up"),
					new Beat(startTime+gap*222,"Down"),
					new Beat(startTime+gap*224,"Left"),
					new Beat(startTime+gap*226,"Right"),
					new Beat(startTime+gap*227,"Down"),
					new Beat(startTime+gap*228,"Down"),
					new Beat(startTime+gap*230,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Left"),
					new Beat(startTime+gap*233,"Up"),
					new Beat(startTime+gap*234,"Up"),
					new Beat(startTime+gap*236,"Right"),
					new Beat(startTime+gap*238,"Up"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*241,"Up"),
					new Beat(startTime+gap*242,"Left"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*243,"Left"),
					new Beat(startTime+gap*245,"Right"),
					new Beat(startTime+gap*246,"Down"),
					new Beat(startTime+gap*248,"Down"),
					new Beat(startTime+gap*250,"Right"),
					new Beat(startTime+gap*252,"Up"),
					new Beat(startTime+gap*254,"Left"),
					new Beat(startTime+gap*256,"Up"),
					new Beat(startTime+gap*257,"Left"),
					new Beat(startTime+gap*259,"Right"),
					new Beat(startTime+gap*261,"Up"),
					new Beat(startTime+gap*262,"Down"),
					new Beat(startTime+gap*262,"Up"),
					new Beat(startTime+gap*264,"Up"),
					new Beat(startTime+gap*266,"Down"),
					new Beat(startTime+gap*267,"Left"),
					new Beat(startTime+gap*268,"Right"),
					new Beat(startTime+gap*270,"Down"),
					new Beat(startTime+gap*272,"Left"),
					new Beat(startTime+gap*272,"Right"),
					new Beat(startTime+gap*274,"Up"),
					new Beat(startTime+gap*275,"Left"),
					new Beat(startTime+gap*277,"Up"),
					new Beat(startTime+gap*279,"Up"),
					new Beat(startTime+gap*281,"Right"),
					new Beat(startTime+gap*282,"Up"),
					new Beat(startTime+gap*284,"Down"),
					new Beat(startTime+gap*286,"Up"),
					new Beat(startTime+gap*288,"Up"),
					new Beat(startTime+gap*290,"Down"),
					new Beat(startTime+gap*292,"Left"),
					new Beat(startTime+gap*294,"Right"),
					new Beat(startTime+gap*296,"Down"),
					new Beat(startTime+gap*298,"Down"),
					new Beat(startTime+gap*299,"Right"),
					new Beat(startTime+gap*302,"Up"),
					new Beat(startTime+gap*304,"Down"),
					new Beat(startTime+gap*306,"Left"),
					new Beat(startTime+gap*308,"Right"),
					new Beat(startTime+gap*310,"Down"),
					new Beat(startTime+gap*312,"Down"),
					new Beat(startTime+gap*314,"Right"),
					new Beat(startTime+gap*316,"Up"),
					new Beat(startTime+gap*318,"Right"),
					new Beat(startTime+gap*320,"Up"),
					new Beat(startTime+gap*321,"Up"),
					new Beat(startTime+gap*322,"Down"),
					new Beat(startTime+gap*324,"Left"),
					new Beat(startTime+gap*326,"Right"),
					new Beat(startTime+gap*327,"Down"),
					new Beat(startTime+gap*328,"Down"),
					new Beat(startTime+gap*330,"Right"),
					new Beat(startTime+gap*330,"Up"),
					new Beat(startTime+gap*332,"Left"),
					new Beat(startTime+gap*333,"Up"),
					new Beat(startTime+gap*334,"Up"),
					new Beat(startTime+gap*336,"Right"),
					new Beat(startTime+gap*338,"Up"),
					new Beat(startTime+gap*340,"Down"),
					new Beat(startTime+gap*341,"Up"),
					new Beat(startTime+gap*342,"Up"),
					new Beat(startTime+gap*342,"Down"),
					new Beat(startTime+gap*343,"Left"),
					new Beat(startTime+gap*345,"Right"),
					new Beat(startTime+gap*346,"Down"),
					new Beat(startTime+gap*348,"Down"),
					new Beat(startTime+gap*350,"Right"),
					new Beat(startTime+gap*352,"Up"),
					new Beat(startTime+gap*354,"Left"),
					new Beat(startTime+gap*356,"Up"),
					new Beat(startTime+gap*357,"Left"),
					new Beat(startTime+gap*359,"Right"),
					new Beat(startTime+gap*361,"Up"),
					new Beat(startTime+gap*362,"Down"),
					new Beat(startTime+gap*362,"Up"),
					new Beat(startTime+gap*364,"Up"),
					new Beat(startTime+gap*366,"Down"),
					new Beat(startTime+gap*367,"Left"),
					new Beat(startTime+gap*368,"Right"),
					new Beat(startTime+gap*370,"Down"),
					new Beat(startTime+gap*372,"Left"),
					new Beat(startTime+gap*372,"Right"),
					new Beat(startTime+gap*374,"Up"),
					new Beat(startTime+gap*375,"Left"),
					new Beat(startTime+gap*377,"Up"),
					new Beat(startTime+gap*379,"Up"),
					new Beat(startTime+gap*381,"Right"),
					new Beat(startTime+gap*382,"Up"),
					new Beat(startTime+gap*384,"Down"),
					new Beat(startTime+gap*386,"Up"),
					new Beat(startTime+gap*388,"Up"),
					new Beat(startTime+gap*390,"Down"),
					new Beat(startTime+gap*392,"Left"),
					new Beat(startTime+gap*394,"Right"),
					new Beat(startTime+gap*396,"Down"),
					new Beat(startTime+gap*398,"Down"),
					new Beat(startTime+gap*399,"Right"),
					new Beat(startTime+gap*402,"Up"),
					new Beat(startTime+gap*404,"Down"),
					new Beat(startTime+gap*406,"Left"),
					new Beat(startTime+gap*408,"Right"),
					new Beat(startTime+gap*410,"Down"),
					new Beat(startTime+gap*412,"Down"),
					new Beat(startTime+gap*414,"Right"),
					new Beat(startTime+gap*416,"Up"),
					new Beat(startTime+gap*418,"Right"),
					new Beat(startTime+gap*420,"Up"),
					new Beat(startTime+gap*421,"Up"),
					new Beat(startTime+gap*422,"Down"),
					new Beat(startTime+gap*424,"Left"),
					new Beat(startTime+gap*426,"Right"),
					new Beat(startTime+gap*427,"Down"),
					new Beat(startTime+gap*428,"Down"),
					new Beat(startTime+gap*430,"Right"),
					new Beat(startTime+gap*430,"Up"),
					new Beat(startTime+gap*432,"Left"),
					new Beat(startTime+gap*433,"Up"),
					new Beat(startTime+gap*434,"Up"),
					new Beat(startTime+gap*436,"Right"),
					new Beat(startTime+gap*438,"Up"),
					new Beat(startTime+gap*440,"Down"),
					new Beat(startTime+gap*441,"Up"),
					new Beat(startTime+gap*442,"Up"),
					new Beat(startTime+gap*442,"Down"),
					new Beat(startTime+gap*443,"Left"),
					new Beat(startTime+gap*445,"Right"),
					new Beat(startTime+gap*446,"Down"),
					new Beat(startTime+gap*448,"Down"),
					new Beat(startTime+gap*450,"Right"),
					new Beat(startTime+gap*452,"Up"),
					new Beat(startTime+gap*454,"Left"),
					new Beat(startTime+gap*456,"Up"),
					new Beat(startTime+gap*457,"Left"),
					new Beat(startTime+gap*459,"Right"),
					new Beat(startTime+gap*461,"Up"),
					new Beat(startTime+gap*462,"Down"),
					new Beat(startTime+gap*462,"Up"),
					new Beat(startTime+gap*464,"Up"),
					new Beat(startTime+gap*466,"Down"),
					new Beat(startTime+gap*467,"Left"),
					new Beat(startTime+gap*468,"Right"),
					new Beat(startTime+gap*470,"Down"),
					new Beat(startTime+gap*472,"Left"),
					new Beat(startTime+gap*472,"Right"),
					new Beat(startTime+gap*474,"Up"),
					new Beat(startTime+gap*475,"Left"),
					new Beat(startTime+gap*477,"Up"),
					new Beat(startTime+gap*479,"Up"),
					new Beat(startTime+gap*481,"Right"),
					new Beat(startTime+gap*482,"Up"),
					new Beat(startTime+gap*484,"Down"),
					new Beat(startTime+gap*486,"Up"),
					new Beat(startTime+gap*488,"Up"),
					new Beat(startTime+gap*490,"Down"),
					new Beat(startTime+gap*492,"Left"),
					new Beat(startTime+gap*494,"Right"),
					new Beat(startTime+gap*494,"Down"),
			};
		}
		if(titleName.equals("hotline")&&difficulty.equals("easy")){
			int startTime =  1000-Main.REACH_TIME*1000;
			int gap = 500;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Left"),
					new Beat(startTime+gap*22,"Left"),
					new Beat(startTime+gap*24,"Down"),
					new Beat(startTime+gap*26,"Left"),
					new Beat(startTime+gap*28,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Up"),
					new Beat(startTime+gap*34,"Down"),
					new Beat(startTime+gap*36,"Left"),
					new Beat(startTime+gap*38,"Right"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*44,"Right"),
					new Beat(startTime+gap*46,"Up"),
					new Beat(startTime+gap*48,"Right"),
					new Beat(startTime+gap*50,"Left"),
					new Beat(startTime+gap*52,"Left"),
					new Beat(startTime+gap*54,"Down"),
					new Beat(startTime+gap*56,"Left"),
					new Beat(startTime+gap*58,"Right"),
					new Beat(startTime+gap*60,"Up"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Down"),
					new Beat(startTime+gap*66,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Down"),
					new Beat(startTime+gap*74,"Right"),
					new Beat(startTime+gap*76,"Up"),
					new Beat(startTime+gap*78,"Right"),
					new Beat(startTime+gap*80,"Left"),
					new Beat(startTime+gap*82,"Left"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Left"),
					new Beat(startTime+gap*88,"Right"),
					new Beat(startTime+gap*90,"Up"),
					new Beat(startTime+gap*92,"Up"),
					new Beat(startTime+gap*94,"Down"),
					new Beat(startTime+gap*96,"Left"),
					new Beat(startTime+gap*98,"Right"),
					new Beat(startTime+gap*100,"Down"),
					new Beat(startTime+gap*102,"Down"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Right"),
					new Beat(startTime+gap*110,"Down"),
					new Beat(startTime+gap*112,"Down"),
					new Beat(startTime+gap*114,"Right"),
					new Beat(startTime+gap*116,"Up"),
					new Beat(startTime+gap*118,"Right"),
					new Beat(startTime+gap*120,"Left"),
					new Beat(startTime+gap*122,"Left"),
					new Beat(startTime+gap*124,"Down"),
					new Beat(startTime+gap*126,"Left"),
					new Beat(startTime+gap*128,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Up"),
					new Beat(startTime+gap*134,"Down"),
					new Beat(startTime+gap*136,"Left"),
					new Beat(startTime+gap*138,"Right"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*142,"Down"),
					new Beat(startTime+gap*144,"Right"),
					new Beat(startTime+gap*146,"Up"),
					new Beat(startTime+gap*148,"Right"),
					new Beat(startTime+gap*150,"Left"),
					new Beat(startTime+gap*152,"Left"),
					new Beat(startTime+gap*154,"Down"),
					new Beat(startTime+gap*156,"Left"),
					new Beat(startTime+gap*158,"Right"),
					new Beat(startTime+gap*160,"Up"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Down"),
					new Beat(startTime+gap*166,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Down"),
					new Beat(startTime+gap*174,"Right"),
					new Beat(startTime+gap*176,"Up"),
					new Beat(startTime+gap*178,"Right"),
					new Beat(startTime+gap*180,"Left"),
					new Beat(startTime+gap*182,"Left"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Left"),
					new Beat(startTime+gap*188,"Right"),
					new Beat(startTime+gap*190,"Up"),
					new Beat(startTime+gap*192,"Up"),
					new Beat(startTime+gap*194,"Down"),
					new Beat(startTime+gap*196,"Left"),
					new Beat(startTime+gap*198,"Right"),
					new Beat(startTime+gap*200,"Down"),
					new Beat(startTime+gap*202,"Down"),
					new Beat(startTime+gap*204,"Right"),
					new Beat(startTime+gap*206,"Up"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Left"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Down"),
					new Beat(startTime+gap*222,"Left"),
					new Beat(startTime+gap*224,"Down"),
					new Beat(startTime+gap*226,"Left"),
					new Beat(startTime+gap*228,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Up"),
					new Beat(startTime+gap*234,"Down"),
					new Beat(startTime+gap*236,"Left"),
					new Beat(startTime+gap*238,"Right"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*244,"Right")
			};
		}
		if(titleName.equals("hotline")&&difficulty.equals("hard")){
			int startTime =  1000-Main.REACH_TIME*1000;
			int gap = 250;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Up"),
					new Beat(startTime+gap*21,"Up"),
					new Beat(startTime+gap*22,"Down"),
					new Beat(startTime+gap*24,"Left"),
					new Beat(startTime+gap*26,"Right"),
					new Beat(startTime+gap*27,"Down"),
					new Beat(startTime+gap*28,"Down"),
					new Beat(startTime+gap*30,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Left"),
					new Beat(startTime+gap*33,"Up"),
					new Beat(startTime+gap*34,"Up"),
					new Beat(startTime+gap*36,"Right"),
					new Beat(startTime+gap*38,"Up"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*41,"Up"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*42,"Right"),
					new Beat(startTime+gap*43,"Left"),
					new Beat(startTime+gap*45,"Right"),
					new Beat(startTime+gap*46,"Down"),
					new Beat(startTime+gap*48,"Down"),
					new Beat(startTime+gap*50,"Right"),
					new Beat(startTime+gap*52,"Up"),
					new Beat(startTime+gap*54,"Left"),
					new Beat(startTime+gap*56,"Up"),
					new Beat(startTime+gap*57,"Left"),
					new Beat(startTime+gap*59,"Right"),
					new Beat(startTime+gap*61,"Up"),
					new Beat(startTime+gap*62,"Down"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Up"),
					new Beat(startTime+gap*66,"Down"),
					new Beat(startTime+gap*67,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Left"),
					new Beat(startTime+gap*72,"Right"),
					new Beat(startTime+gap*74,"Up"),
					new Beat(startTime+gap*75,"Left"),
					new Beat(startTime+gap*77,"Up"),
					new Beat(startTime+gap*79,"Up"),
					new Beat(startTime+gap*81,"Right"),
					new Beat(startTime+gap*82,"Up"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Up"),
					new Beat(startTime+gap*88,"Up"),
					new Beat(startTime+gap*90,"Down"),
					new Beat(startTime+gap*92,"Left"),
					new Beat(startTime+gap*94,"Right"),
					new Beat(startTime+gap*96,"Down"),
					new Beat(startTime+gap*98,"Down"),
					new Beat(startTime+gap*99,"Right"),
					new Beat(startTime+gap*100,"Up"),
					new Beat(startTime+gap*101,"Left"),
					new Beat(startTime+gap*102,"Up"),
					new Beat(startTime+gap*103,"Up"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Down"),
					new Beat(startTime+gap*110,"Up"),
					new Beat(startTime+gap*120,"Up"),
					new Beat(startTime+gap*121,"Up"),
					new Beat(startTime+gap*122,"Down"),
					new Beat(startTime+gap*124,"Left"),
					new Beat(startTime+gap*126,"Right"),
					new Beat(startTime+gap*127,"Down"),
					new Beat(startTime+gap*128,"Down"),
					new Beat(startTime+gap*130,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Left"),
					new Beat(startTime+gap*133,"Up"),
					new Beat(startTime+gap*134,"Up"),
					new Beat(startTime+gap*136,"Right"),
					new Beat(startTime+gap*138,"Up"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*141,"Up"),
					new Beat(startTime+gap*142,"Up"),
					new Beat(startTime+gap*142,"Left"),
					new Beat(startTime+gap*143,"Left"),
					new Beat(startTime+gap*145,"Right"),
					new Beat(startTime+gap*146,"Down"),
					new Beat(startTime+gap*148,"Down"),
					new Beat(startTime+gap*150,"Right"),
					new Beat(startTime+gap*152,"Up"),
					new Beat(startTime+gap*154,"Left"),
					new Beat(startTime+gap*156,"Up"),
					new Beat(startTime+gap*157,"Left"),
					new Beat(startTime+gap*159,"Right"),
					new Beat(startTime+gap*161,"Up"),
					new Beat(startTime+gap*162,"Down"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Up"),
					new Beat(startTime+gap*166,"Down"),
					new Beat(startTime+gap*167,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Left"),
					new Beat(startTime+gap*172,"Right"),
					new Beat(startTime+gap*174,"Up"),
					new Beat(startTime+gap*175,"Left"),
					new Beat(startTime+gap*177,"Up"),
					new Beat(startTime+gap*179,"Up"),
					new Beat(startTime+gap*181,"Right"),
					new Beat(startTime+gap*182,"Up"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Up"),
					new Beat(startTime+gap*188,"Up"),
					new Beat(startTime+gap*190,"Down"),
					new Beat(startTime+gap*192,"Left"),
					new Beat(startTime+gap*194,"Right"),
					new Beat(startTime+gap*196,"Down"),
					new Beat(startTime+gap*198,"Down"),
					new Beat(startTime+gap*199,"Right"),
					new Beat(startTime+gap*202,"Up"),
					new Beat(startTime+gap*204,"Down"),
					new Beat(startTime+gap*206,"Left"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Down"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Up"),
					new Beat(startTime+gap*221,"Up"),
					new Beat(startTime+gap*222,"Down"),
					new Beat(startTime+gap*224,"Left"),
					new Beat(startTime+gap*226,"Right"),
					new Beat(startTime+gap*227,"Down"),
					new Beat(startTime+gap*228,"Down"),
					new Beat(startTime+gap*230,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Left"),
					new Beat(startTime+gap*233,"Up"),
					new Beat(startTime+gap*234,"Up"),
					new Beat(startTime+gap*236,"Right"),
					new Beat(startTime+gap*238,"Up"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*241,"Up"),
					new Beat(startTime+gap*242,"Left"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*243,"Left"),
					new Beat(startTime+gap*245,"Right"),
					new Beat(startTime+gap*246,"Down"),
					new Beat(startTime+gap*248,"Down"),
					new Beat(startTime+gap*250,"Right"),
					new Beat(startTime+gap*252,"Up"),
					new Beat(startTime+gap*254,"Left"),
					new Beat(startTime+gap*256,"Up"),
					new Beat(startTime+gap*257,"Left"),
					new Beat(startTime+gap*259,"Right"),
					new Beat(startTime+gap*261,"Up"),
					new Beat(startTime+gap*262,"Down"),
					new Beat(startTime+gap*262,"Up"),
					new Beat(startTime+gap*264,"Up"),
					new Beat(startTime+gap*266,"Down"),
					new Beat(startTime+gap*267,"Left"),
					new Beat(startTime+gap*268,"Right"),
					new Beat(startTime+gap*270,"Down"),
					new Beat(startTime+gap*272,"Left"),
					new Beat(startTime+gap*272,"Right"),
					new Beat(startTime+gap*274,"Up"),
					new Beat(startTime+gap*275,"Left"),
					new Beat(startTime+gap*277,"Up"),
					new Beat(startTime+gap*279,"Up"),
					new Beat(startTime+gap*281,"Right"),
					new Beat(startTime+gap*282,"Up"),
					new Beat(startTime+gap*284,"Down"),
					new Beat(startTime+gap*286,"Up"),
					new Beat(startTime+gap*288,"Up"),
					new Beat(startTime+gap*290,"Down"),
					new Beat(startTime+gap*292,"Left"),
					new Beat(startTime+gap*294,"Right"),
					new Beat(startTime+gap*296,"Down"),
					new Beat(startTime+gap*298,"Down"),
					new Beat(startTime+gap*299,"Right"),
					new Beat(startTime+gap*302,"Up"),
					new Beat(startTime+gap*304,"Down"),
					new Beat(startTime+gap*306,"Left"),
					new Beat(startTime+gap*308,"Right"),
					new Beat(startTime+gap*310,"Down"),
					new Beat(startTime+gap*312,"Down"),
					new Beat(startTime+gap*314,"Right"),
					new Beat(startTime+gap*316,"Up"),
					new Beat(startTime+gap*318,"Right"),
					new Beat(startTime+gap*320,"Up"),
					new Beat(startTime+gap*321,"Up"),
					new Beat(startTime+gap*322,"Down"),
					new Beat(startTime+gap*324,"Left"),
					new Beat(startTime+gap*326,"Right"),
					new Beat(startTime+gap*327,"Down"),
					new Beat(startTime+gap*328,"Down"),
					new Beat(startTime+gap*330,"Right"),
					new Beat(startTime+gap*330,"Up"),
					new Beat(startTime+gap*332,"Left"),
					new Beat(startTime+gap*333,"Up"),
					new Beat(startTime+gap*334,"Up"),
					new Beat(startTime+gap*336,"Right"),
					new Beat(startTime+gap*338,"Up"),
					new Beat(startTime+gap*340,"Down"),
					new Beat(startTime+gap*341,"Up"),
					new Beat(startTime+gap*342,"Up"),
					new Beat(startTime+gap*342,"Down"),
					new Beat(startTime+gap*343,"Left"),
					new Beat(startTime+gap*345,"Right"),
					new Beat(startTime+gap*346,"Down"),
					new Beat(startTime+gap*348,"Down"),
					new Beat(startTime+gap*350,"Right"),
					new Beat(startTime+gap*352,"Up"),
					new Beat(startTime+gap*354,"Left"),
					new Beat(startTime+gap*356,"Up"),
					new Beat(startTime+gap*357,"Left"),
					new Beat(startTime+gap*359,"Right"),
					new Beat(startTime+gap*361,"Up"),
					new Beat(startTime+gap*362,"Down"),
					new Beat(startTime+gap*362,"Up"),
					new Beat(startTime+gap*364,"Up"),
					new Beat(startTime+gap*366,"Down"),
					new Beat(startTime+gap*367,"Left"),
					new Beat(startTime+gap*368,"Right"),
					new Beat(startTime+gap*370,"Down"),
					new Beat(startTime+gap*372,"Left"),
					new Beat(startTime+gap*372,"Right"),
					new Beat(startTime+gap*374,"Up"),
					new Beat(startTime+gap*375,"Left"),
					new Beat(startTime+gap*377,"Up"),
					new Beat(startTime+gap*379,"Up"),
					new Beat(startTime+gap*381,"Right"),
					new Beat(startTime+gap*382,"Up"),
					new Beat(startTime+gap*384,"Down"),
					new Beat(startTime+gap*386,"Up"),
					new Beat(startTime+gap*388,"Up"),
					new Beat(startTime+gap*390,"Down"),
					new Beat(startTime+gap*392,"Left"),
					new Beat(startTime+gap*394,"Right"),
					new Beat(startTime+gap*396,"Down"),
					new Beat(startTime+gap*398,"Down"),
					new Beat(startTime+gap*399,"Right"),
					new Beat(startTime+gap*402,"Up"),
					new Beat(startTime+gap*404,"Down"),
					new Beat(startTime+gap*406,"Left"),
					new Beat(startTime+gap*408,"Right"),
					new Beat(startTime+gap*410,"Down"),
					new Beat(startTime+gap*412,"Down"),
					new Beat(startTime+gap*414,"Right"),
					new Beat(startTime+gap*416,"Up"),
					new Beat(startTime+gap*418,"Right"),
					new Beat(startTime+gap*420,"Up"),
					new Beat(startTime+gap*421,"Up"),
					new Beat(startTime+gap*422,"Down"),
					new Beat(startTime+gap*424,"Left"),
					new Beat(startTime+gap*426,"Right"),
					new Beat(startTime+gap*427,"Down"),
					new Beat(startTime+gap*428,"Down"),
					new Beat(startTime+gap*430,"Right"),
					new Beat(startTime+gap*430,"Up"),
					new Beat(startTime+gap*432,"Left"),
					new Beat(startTime+gap*433,"Up"),
					new Beat(startTime+gap*434,"Up"),
					new Beat(startTime+gap*436,"Right"),
					new Beat(startTime+gap*438,"Up"),
					new Beat(startTime+gap*440,"Down"),
					new Beat(startTime+gap*441,"Up"),
					new Beat(startTime+gap*442,"Up"),
					new Beat(startTime+gap*442,"Down"),
					new Beat(startTime+gap*443,"Left"),
					new Beat(startTime+gap*445,"Right"),
					new Beat(startTime+gap*446,"Down"),
					new Beat(startTime+gap*448,"Down"),
					new Beat(startTime+gap*450,"Right"),
					new Beat(startTime+gap*452,"Up"),
					new Beat(startTime+gap*454,"Left"),
					new Beat(startTime+gap*456,"Up"),
					new Beat(startTime+gap*457,"Left"),
					new Beat(startTime+gap*459,"Right"),
					new Beat(startTime+gap*461,"Up"),
					new Beat(startTime+gap*462,"Down"),
					new Beat(startTime+gap*462,"Up"),
					new Beat(startTime+gap*464,"Up"),
					new Beat(startTime+gap*466,"Down"),
					new Beat(startTime+gap*467,"Left"),
					new Beat(startTime+gap*468,"Right"),
					new Beat(startTime+gap*470,"Down"),
					new Beat(startTime+gap*472,"Left"),
					new Beat(startTime+gap*472,"Right"),
					new Beat(startTime+gap*474,"Up"),
					new Beat(startTime+gap*475,"Left"),
					new Beat(startTime+gap*477,"Up"),
					new Beat(startTime+gap*479,"Up"),
					new Beat(startTime+gap*481,"Right"),
					new Beat(startTime+gap*482,"Up"),
					new Beat(startTime+gap*484,"Down"),
					new Beat(startTime+gap*486,"Up"),
					new Beat(startTime+gap*488,"Up"),
					new Beat(startTime+gap*490,"Down"),
					new Beat(startTime+gap*492,"Left"),
					new Beat(startTime+gap*494,"Right"),
					new Beat(startTime+gap*494,"Down"),
			};
		}
		if(titleName.equals("mom")){
			int startTime =  1000-Main.REACH_TIME*1000;
			int gap = 500;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Left"),
					new Beat(startTime+gap*22,"Left"),
					new Beat(startTime+gap*24,"Down"),
					new Beat(startTime+gap*26,"Left"),
					new Beat(startTime+gap*28,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Up"),
					new Beat(startTime+gap*34,"Down"),
					new Beat(startTime+gap*36,"Left"),
					new Beat(startTime+gap*38,"Right"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*44,"Right"),
					new Beat(startTime+gap*46,"Up"),
					new Beat(startTime+gap*48,"Right"),
					new Beat(startTime+gap*50,"Left"),
					new Beat(startTime+gap*52,"Left"),
					new Beat(startTime+gap*54,"Down"),
					new Beat(startTime+gap*56,"Left"),
					new Beat(startTime+gap*58,"Right"),
					new Beat(startTime+gap*60,"Up"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Down"),
					new Beat(startTime+gap*66,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Down"),
					new Beat(startTime+gap*74,"Right"),
					new Beat(startTime+gap*76,"Up"),
					new Beat(startTime+gap*78,"Right"),
					new Beat(startTime+gap*80,"Left"),
					new Beat(startTime+gap*82,"Left"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Left"),
					new Beat(startTime+gap*88,"Right"),
					new Beat(startTime+gap*90,"Up"),
					new Beat(startTime+gap*92,"Up"),
					new Beat(startTime+gap*94,"Down"),
					new Beat(startTime+gap*96,"Left"),
					new Beat(startTime+gap*98,"Right"),
					new Beat(startTime+gap*100,"Down"),
					new Beat(startTime+gap*102,"Down"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Right"),
					new Beat(startTime+gap*110,"Down"),
					new Beat(startTime+gap*112,"Down"),
					new Beat(startTime+gap*114,"Right"),
					new Beat(startTime+gap*116,"Up"),
					new Beat(startTime+gap*118,"Right"),
					new Beat(startTime+gap*120,"Left"),
					new Beat(startTime+gap*122,"Left"),
					new Beat(startTime+gap*124,"Down"),
					new Beat(startTime+gap*126,"Left"),
					new Beat(startTime+gap*128,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Up"),
					new Beat(startTime+gap*134,"Down"),
					new Beat(startTime+gap*136,"Left"),
					new Beat(startTime+gap*138,"Right"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*142,"Down"),
					new Beat(startTime+gap*144,"Right"),
					new Beat(startTime+gap*146,"Up"),
					new Beat(startTime+gap*148,"Right"),
					new Beat(startTime+gap*150,"Left"),
					new Beat(startTime+gap*152,"Left"),
					new Beat(startTime+gap*154,"Down"),
					new Beat(startTime+gap*156,"Left"),
					new Beat(startTime+gap*158,"Right"),
					new Beat(startTime+gap*160,"Up"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Down"),
					new Beat(startTime+gap*166,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Down"),
					new Beat(startTime+gap*174,"Right"),
					new Beat(startTime+gap*176,"Up"),
					new Beat(startTime+gap*178,"Right"),
					new Beat(startTime+gap*180,"Left"),
					new Beat(startTime+gap*182,"Left"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Left"),
					new Beat(startTime+gap*188,"Right"),
					new Beat(startTime+gap*190,"Up"),
					new Beat(startTime+gap*192,"Up"),
					new Beat(startTime+gap*194,"Down"),
					new Beat(startTime+gap*196,"Left"),
					new Beat(startTime+gap*198,"Right"),
					new Beat(startTime+gap*200,"Down"),
					new Beat(startTime+gap*202,"Down"),
					new Beat(startTime+gap*204,"Right"),
					new Beat(startTime+gap*206,"Up"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Left"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Down"),
					new Beat(startTime+gap*222,"Left"),
					new Beat(startTime+gap*224,"Down"),
					new Beat(startTime+gap*226,"Left"),
					new Beat(startTime+gap*228,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Up"),
					new Beat(startTime+gap*234,"Down"),
					new Beat(startTime+gap*236,"Left"),
					new Beat(startTime+gap*238,"Right"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*244,"Right")
			};
		}
		if(titleName.equals("mom")&&difficulty.equals("hard")){
			int startTime =  1000-Main.REACH_TIME*1000;
			int gap = 250;
			beats = new Beat[]{
					new Beat(startTime,"Up"),
					new Beat(startTime+gap*2,"Up"),
					new Beat(startTime+gap*4,"Down"),
					new Beat(startTime+gap*6,"Left"),
					new Beat(startTime+gap*8,"Right"),
					new Beat(startTime+gap*10,"Down"),
					new Beat(startTime+gap*12,"Down"),
					new Beat(startTime+gap*14,"Right"),
					new Beat(startTime+gap*16,"Up"),
					new Beat(startTime+gap*18,"Right"),
					new Beat(startTime+gap*20,"Up"),
					new Beat(startTime+gap*21,"Up"),
					new Beat(startTime+gap*22,"Down"),
					new Beat(startTime+gap*24,"Left"),
					new Beat(startTime+gap*26,"Right"),
					new Beat(startTime+gap*27,"Down"),
					new Beat(startTime+gap*28,"Down"),
					new Beat(startTime+gap*30,"Right"),
					new Beat(startTime+gap*30,"Up"),
					new Beat(startTime+gap*32,"Left"),
					new Beat(startTime+gap*33,"Up"),
					new Beat(startTime+gap*34,"Up"),
					new Beat(startTime+gap*36,"Right"),
					new Beat(startTime+gap*38,"Up"),
					new Beat(startTime+gap*40,"Down"),
					new Beat(startTime+gap*41,"Up"),
					new Beat(startTime+gap*42,"Down"),
					new Beat(startTime+gap*42,"Right"),
					new Beat(startTime+gap*43,"Left"),
					new Beat(startTime+gap*45,"Right"),
					new Beat(startTime+gap*46,"Down"),
					new Beat(startTime+gap*48,"Down"),
					new Beat(startTime+gap*50,"Right"),
					new Beat(startTime+gap*52,"Up"),
					new Beat(startTime+gap*54,"Left"),
					new Beat(startTime+gap*56,"Up"),
					new Beat(startTime+gap*57,"Left"),
					new Beat(startTime+gap*59,"Right"),
					new Beat(startTime+gap*61,"Up"),
					new Beat(startTime+gap*62,"Down"),
					new Beat(startTime+gap*62,"Up"),
					new Beat(startTime+gap*64,"Up"),
					new Beat(startTime+gap*66,"Down"),
					new Beat(startTime+gap*67,"Left"),
					new Beat(startTime+gap*68,"Right"),
					new Beat(startTime+gap*70,"Down"),
					new Beat(startTime+gap*72,"Left"),
					new Beat(startTime+gap*72,"Right"),
					new Beat(startTime+gap*74,"Up"),
					new Beat(startTime+gap*75,"Left"),
					new Beat(startTime+gap*77,"Up"),
					new Beat(startTime+gap*79,"Up"),
					new Beat(startTime+gap*81,"Right"),
					new Beat(startTime+gap*82,"Up"),
					new Beat(startTime+gap*84,"Down"),
					new Beat(startTime+gap*86,"Up"),
					new Beat(startTime+gap*88,"Up"),
					new Beat(startTime+gap*90,"Down"),
					new Beat(startTime+gap*92,"Left"),
					new Beat(startTime+gap*94,"Right"),
					new Beat(startTime+gap*96,"Down"),
					new Beat(startTime+gap*98,"Down"),
					new Beat(startTime+gap*99,"Right"),
					new Beat(startTime+gap*100,"Up"),
					new Beat(startTime+gap*101,"Left"),
					new Beat(startTime+gap*102,"Up"),
					new Beat(startTime+gap*103,"Up"),
					new Beat(startTime+gap*104,"Right"),
					new Beat(startTime+gap*106,"Up"),
					new Beat(startTime+gap*108,"Down"),
					new Beat(startTime+gap*110,"Up"),
					new Beat(startTime+gap*120,"Up"),
					new Beat(startTime+gap*121,"Up"),
					new Beat(startTime+gap*122,"Down"),
					new Beat(startTime+gap*124,"Left"),
					new Beat(startTime+gap*126,"Right"),
					new Beat(startTime+gap*127,"Down"),
					new Beat(startTime+gap*128,"Down"),
					new Beat(startTime+gap*130,"Right"),
					new Beat(startTime+gap*130,"Up"),
					new Beat(startTime+gap*132,"Left"),
					new Beat(startTime+gap*133,"Up"),
					new Beat(startTime+gap*134,"Up"),
					new Beat(startTime+gap*136,"Right"),
					new Beat(startTime+gap*138,"Up"),
					new Beat(startTime+gap*140,"Down"),
					new Beat(startTime+gap*141,"Up"),
					new Beat(startTime+gap*142,"Up"),
					new Beat(startTime+gap*142,"Left"),
					new Beat(startTime+gap*143,"Left"),
					new Beat(startTime+gap*145,"Right"),
					new Beat(startTime+gap*146,"Down"),
					new Beat(startTime+gap*148,"Down"),
					new Beat(startTime+gap*150,"Right"),
					new Beat(startTime+gap*152,"Up"),
					new Beat(startTime+gap*154,"Left"),
					new Beat(startTime+gap*156,"Up"),
					new Beat(startTime+gap*157,"Left"),
					new Beat(startTime+gap*159,"Right"),
					new Beat(startTime+gap*161,"Up"),
					new Beat(startTime+gap*162,"Down"),
					new Beat(startTime+gap*162,"Up"),
					new Beat(startTime+gap*164,"Up"),
					new Beat(startTime+gap*166,"Down"),
					new Beat(startTime+gap*167,"Left"),
					new Beat(startTime+gap*168,"Right"),
					new Beat(startTime+gap*170,"Down"),
					new Beat(startTime+gap*172,"Left"),
					new Beat(startTime+gap*172,"Right"),
					new Beat(startTime+gap*174,"Up"),
					new Beat(startTime+gap*175,"Left"),
					new Beat(startTime+gap*177,"Up"),
					new Beat(startTime+gap*179,"Up"),
					new Beat(startTime+gap*181,"Right"),
					new Beat(startTime+gap*182,"Up"),
					new Beat(startTime+gap*184,"Down"),
					new Beat(startTime+gap*186,"Up"),
					new Beat(startTime+gap*188,"Up"),
					new Beat(startTime+gap*190,"Down"),
					new Beat(startTime+gap*192,"Left"),
					new Beat(startTime+gap*194,"Right"),
					new Beat(startTime+gap*196,"Down"),
					new Beat(startTime+gap*198,"Down"),
					new Beat(startTime+gap*199,"Right"),
					new Beat(startTime+gap*202,"Up"),
					new Beat(startTime+gap*204,"Down"),
					new Beat(startTime+gap*206,"Left"),
					new Beat(startTime+gap*208,"Right"),
					new Beat(startTime+gap*210,"Down"),
					new Beat(startTime+gap*212,"Down"),
					new Beat(startTime+gap*214,"Right"),
					new Beat(startTime+gap*216,"Up"),
					new Beat(startTime+gap*218,"Right"),
					new Beat(startTime+gap*220,"Up"),
					new Beat(startTime+gap*221,"Up"),
					new Beat(startTime+gap*222,"Down"),
					new Beat(startTime+gap*224,"Left"),
					new Beat(startTime+gap*226,"Right"),
					new Beat(startTime+gap*227,"Down"),
					new Beat(startTime+gap*228,"Down"),
					new Beat(startTime+gap*230,"Right"),
					new Beat(startTime+gap*230,"Up"),
					new Beat(startTime+gap*232,"Left"),
					new Beat(startTime+gap*233,"Up"),
					new Beat(startTime+gap*234,"Up"),
					new Beat(startTime+gap*236,"Right"),
					new Beat(startTime+gap*238,"Up"),
					new Beat(startTime+gap*240,"Down"),
					new Beat(startTime+gap*241,"Up"),
					new Beat(startTime+gap*242,"Left"),
					new Beat(startTime+gap*242,"Down"),
					new Beat(startTime+gap*243,"Left"),
					new Beat(startTime+gap*245,"Right"),
					new Beat(startTime+gap*246,"Down"),
					new Beat(startTime+gap*248,"Down"),
					new Beat(startTime+gap*250,"Right"),
					new Beat(startTime+gap*252,"Up"),
					new Beat(startTime+gap*254,"Left"),
					new Beat(startTime+gap*256,"Up"),
					new Beat(startTime+gap*257,"Left"),
					new Beat(startTime+gap*259,"Right"),
					new Beat(startTime+gap*261,"Up"),
					new Beat(startTime+gap*262,"Down"),
					new Beat(startTime+gap*262,"Up"),
					new Beat(startTime+gap*264,"Up"),
					new Beat(startTime+gap*266,"Down"),
					new Beat(startTime+gap*267,"Left"),
					new Beat(startTime+gap*268,"Right"),
					new Beat(startTime+gap*270,"Down"),
					new Beat(startTime+gap*272,"Left"),
					new Beat(startTime+gap*272,"Right"),
					new Beat(startTime+gap*274,"Up"),
					new Beat(startTime+gap*275,"Left"),
					new Beat(startTime+gap*277,"Up"),
					new Beat(startTime+gap*279,"Up"),
					new Beat(startTime+gap*281,"Right"),
					new Beat(startTime+gap*282,"Up"),
					new Beat(startTime+gap*284,"Down"),
					new Beat(startTime+gap*286,"Up"),
					new Beat(startTime+gap*288,"Up"),
					new Beat(startTime+gap*290,"Down"),
					new Beat(startTime+gap*292,"Left"),
					new Beat(startTime+gap*294,"Right"),
					new Beat(startTime+gap*296,"Down"),
					new Beat(startTime+gap*298,"Down"),
					new Beat(startTime+gap*299,"Right"),
					new Beat(startTime+gap*302,"Up"),
					new Beat(startTime+gap*304,"Down"),
					new Beat(startTime+gap*306,"Left"),
					new Beat(startTime+gap*308,"Right"),
					new Beat(startTime+gap*310,"Down"),
					new Beat(startTime+gap*312,"Down"),
					new Beat(startTime+gap*314,"Right"),
					new Beat(startTime+gap*316,"Up"),
					new Beat(startTime+gap*318,"Right"),
					new Beat(startTime+gap*320,"Up"),
					new Beat(startTime+gap*321,"Up"),
					new Beat(startTime+gap*322,"Down"),
					new Beat(startTime+gap*324,"Left"),
					new Beat(startTime+gap*326,"Right"),
					new Beat(startTime+gap*327,"Down"),
					new Beat(startTime+gap*328,"Down"),
					new Beat(startTime+gap*330,"Right"),
					new Beat(startTime+gap*330,"Up"),
					new Beat(startTime+gap*332,"Left"),
					new Beat(startTime+gap*333,"Up"),
					new Beat(startTime+gap*334,"Up"),
					new Beat(startTime+gap*336,"Right"),
					new Beat(startTime+gap*338,"Up"),
					new Beat(startTime+gap*340,"Down"),
					new Beat(startTime+gap*341,"Up"),
					new Beat(startTime+gap*342,"Up"),
					new Beat(startTime+gap*342,"Down"),
					new Beat(startTime+gap*343,"Left"),
					new Beat(startTime+gap*345,"Right"),
					new Beat(startTime+gap*346,"Down"),
					new Beat(startTime+gap*348,"Down"),
					new Beat(startTime+gap*350,"Right"),
					new Beat(startTime+gap*352,"Up"),
					new Beat(startTime+gap*354,"Left"),
					new Beat(startTime+gap*356,"Up"),
					new Beat(startTime+gap*357,"Left"),
					new Beat(startTime+gap*359,"Right"),
					new Beat(startTime+gap*361,"Up"),
					new Beat(startTime+gap*362,"Down"),
					new Beat(startTime+gap*362,"Up"),
					new Beat(startTime+gap*364,"Up"),
					new Beat(startTime+gap*366,"Down"),
					new Beat(startTime+gap*367,"Left"),
					new Beat(startTime+gap*368,"Right"),
					new Beat(startTime+gap*370,"Down"),
					new Beat(startTime+gap*372,"Left"),
					new Beat(startTime+gap*372,"Right"),
					new Beat(startTime+gap*374,"Up"),
					new Beat(startTime+gap*375,"Left"),
					new Beat(startTime+gap*377,"Up"),
					new Beat(startTime+gap*379,"Up"),
					new Beat(startTime+gap*381,"Right"),
					new Beat(startTime+gap*382,"Up"),
					new Beat(startTime+gap*384,"Down"),
					new Beat(startTime+gap*386,"Up"),
					new Beat(startTime+gap*388,"Up"),
					new Beat(startTime+gap*390,"Down"),
					new Beat(startTime+gap*392,"Left"),
					new Beat(startTime+gap*394,"Right"),
					new Beat(startTime+gap*396,"Down"),
					new Beat(startTime+gap*398,"Down"),
					new Beat(startTime+gap*399,"Right"),
					new Beat(startTime+gap*402,"Up"),
					new Beat(startTime+gap*404,"Down"),
					new Beat(startTime+gap*406,"Left"),
					new Beat(startTime+gap*408,"Right"),
					new Beat(startTime+gap*410,"Down"),
					new Beat(startTime+gap*412,"Down"),
					new Beat(startTime+gap*414,"Right"),
					new Beat(startTime+gap*416,"Up"),
					new Beat(startTime+gap*418,"Right"),
					new Beat(startTime+gap*420,"Up"),
					new Beat(startTime+gap*421,"Up"),
					new Beat(startTime+gap*422,"Down"),
					new Beat(startTime+gap*424,"Left"),
					new Beat(startTime+gap*426,"Right"),
					new Beat(startTime+gap*427,"Down"),
					new Beat(startTime+gap*428,"Down"),
					new Beat(startTime+gap*430,"Right"),
					new Beat(startTime+gap*430,"Up"),
					new Beat(startTime+gap*432,"Left"),
					new Beat(startTime+gap*433,"Up"),
					new Beat(startTime+gap*434,"Up"),
					new Beat(startTime+gap*436,"Right"),
					new Beat(startTime+gap*438,"Up"),
					new Beat(startTime+gap*440,"Down"),
					new Beat(startTime+gap*441,"Up"),
					new Beat(startTime+gap*442,"Up"),
					new Beat(startTime+gap*442,"Down"),
					new Beat(startTime+gap*443,"Left"),
					new Beat(startTime+gap*445,"Right"),
					new Beat(startTime+gap*446,"Down"),
					new Beat(startTime+gap*448,"Down"),
					new Beat(startTime+gap*450,"Right"),
					new Beat(startTime+gap*452,"Up"),
					new Beat(startTime+gap*454,"Left"),
					new Beat(startTime+gap*456,"Up"),
					new Beat(startTime+gap*457,"Left"),
					new Beat(startTime+gap*459,"Right"),
					new Beat(startTime+gap*461,"Up"),
					new Beat(startTime+gap*462,"Down"),
					new Beat(startTime+gap*462,"Up"),
					new Beat(startTime+gap*464,"Up"),
					new Beat(startTime+gap*466,"Down"),
					new Beat(startTime+gap*467,"Left"),
					new Beat(startTime+gap*468,"Right"),
					new Beat(startTime+gap*470,"Down"),
					new Beat(startTime+gap*472,"Left"),
					new Beat(startTime+gap*472,"Right"),
					new Beat(startTime+gap*474,"Up"),
					new Beat(startTime+gap*475,"Left"),
					new Beat(startTime+gap*477,"Up"),
					new Beat(startTime+gap*479,"Up"),
					new Beat(startTime+gap*481,"Right"),
					new Beat(startTime+gap*482,"Up"),
					new Beat(startTime+gap*484,"Down"),
					new Beat(startTime+gap*486,"Up"),
					new Beat(startTime+gap*488,"Up"),
					new Beat(startTime+gap*490,"Down"),
					new Beat(startTime+gap*492,"Left"),
					new Beat(startTime+gap*494,"Right"),
					new Beat(startTime+gap*494,"Down"),
			};
		}
		int i = 0;
		gameMusic.start();
		while(i<beats.length&&!isInterrupted()){
			boolean raised = false;
			if(beats[i].getTime()<=gameMusic.getTime()){
				Note note = new Note(720,beats[i].getNoteName());
				note.start();
				noteList.add(note);
				i++;
				raised=true;
			}

		}
		
	}
	public void judge(String input){
		for(int i=0;i<noteList.size();i++){
			Note note = noteList.get(i);
			if(input.equals(note.getNoteType())){
				judgeEvent(note.judge());
				judgeScore(note.judge());
				break;
			}
		}
	}
	public void judgeEvent(String judge){
		if(!judge.equals("none")){
			flareimage = new ImageIcon(Main.class.getResource("../images/flareimage.png")).getImage();
		} 
		if(judge.equals("miss")){
			judgeimage = new ImageIcon(Main.class.getResource("../images/miss.png")).getImage();
			
		}else if(judge.equals("good")){
			judgeimage = new ImageIcon(Main.class.getResource("../images/good.png")).getImage();
		}else if(judge.equals("excellent")){
			judgeimage = new ImageIcon(Main.class.getResource("../images/ex.png")).getImage();
		}else if(judge.equals("perfect")){
			judgeimage = new ImageIcon(Main.class.getResource("../images/per.png")).getImage();
		}
	}
	public void judgeScore(String judge){
		if(judge.equals("miss")){
			Score+=0;
		}else if(judge.equals("good")){
			Score+=50;
		}else if(judge.equals("excellent")){
			Score+=150;
		}else if(judge.equals("perfect")){
			Score+=300;
		}
	}
	
}
